---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "skip-changelog"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: 'page-objects'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
  - package-ecosystem: 'npm'
    directory: 'locators'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
