name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        node: [ 16 ]
        version: [ max ]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Dependencies
        run: |
          rm -f package-lock.json
          npm run prepare-deps
          npm install
          npm run build
          npm run prepare-test
      - name: Run Tests
        env: 
          CODE_VERSION: ${{ matrix.version }}
        run: npm test
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-macos-${{ matrix.version }}
          path: test/test-project/test-resources/screenshots/*.png
