name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        node: [15]
        version: [latest]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Dependencies
        run: |
          rm -f package-lock.json
          npm run prepare-deps
          npm install
          npm run build
          npm run prepare-test
      - name: Run Tests
        env: 
          CODE_VERSION: ${{ matrix.version }}
        run: npm test
